version: '3'

services:
  mysql1:
    image: mysql:5.7
    volumes: 
        - sql_storage_new:/var/lib/mysql
    restart: always
    environment:    
       MYSQL_ROOT_PASSWORD: rootpass
       MYSQL_USER: sachin
       MYSQL_PASSWORD: royal
       MYSQL_DATABASE: database

    
  myjoomla1:
        
    image: joomla:latest
    restart: always
    depends_on:
         - mysql1
    ports:
         - 8080:80
    environment:
      JOOMLA_DB_HOST: mysql1
      JOOMLA_DB_USER: sachin
      JOOMLA_DB_PASSWORD: royal
      JOOMLA_DB_NAME: database    
    volumes:
      - joomla_storage_new:/var/www/html
       
volumes:
       sql_storage_new:
       joomla_storage_new:       
